
'use client'

import React from 'react'
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { Button } from '@/components/ui/Button'
import type { Scan } from '@/lib/types'

interface PDFReportBtnProps {
    scan: Scan
}

export function PDFReportBtn({ scan }: PDFReportBtnProps) {
    const generatePDF = () => {
        const doc = new jsPDF()
        const pageWidth = doc.internal.pageSize.width
        const margin = 20

        // Header
        doc.setFontSize(22)
        doc.setTextColor(6, 182, 212) // Cyan color
        doc.text('MedScanX Analysis Report', margin, 20)

        doc.setFontSize(10)
        doc.setTextColor(100)
        doc.text(`Generated: ${new Date().toLocaleString()}`, margin, 28)
        doc.text(`Scan ID: ${scan.id}`, margin, 33)

        // Line separator
        doc.setDrawColor(200)
        doc.line(margin, 38, pageWidth - margin, 38)

        // Patient/Scan Info
        doc.setFontSize(12)
        doc.setTextColor(0)
        doc.text(`Scan Name: ${scan.scan_name}`, margin, 48)

        // Severity Badge (Text representation)
        const severityColor =
            scan.severity === 'critical' ? [220, 38, 38] :
                scan.severity === 'high' ? [234, 88, 12] :
                    scan.severity === 'medium' ? [202, 138, 4] : [22, 163, 74] // RGB values

        doc.setFillColor(severityColor[0], severityColor[1], severityColor[2])
        doc.roundedRect(pageWidth - margin - 40, 42, 40, 10, 2, 2, 'F')
        doc.setTextColor(255)
        doc.setFontSize(10)
        doc.text(scan.severity.toUpperCase(), pageWidth - margin - 35, 48)

        // Reset text color
        doc.setTextColor(0)

        // Analysis Section
        doc.setFontSize(16)
        doc.text('Analysis Findings', margin, 65)

        doc.setFontSize(11)
        const splitAnalysis = doc.splitTextToSize(scan.analysis, pageWidth - (margin * 2))
        doc.text(splitAnalysis, margin, 75)

        let verticalOffset = 75 + (splitAnalysis.length * 5) + 10

        // Tables using autoTable
        const tables = [
            { title: 'Abnormalities Detected', data: scan.abnormalities },
            { title: 'Precautions', data: scan.precautions },
            { title: 'Recommendations', data: scan.recommendations }
        ]

        tables.forEach(section => {
            if (section.data && section.data.length > 0) {
                // @ts-ignore
                autoTable(doc, {
                    startY: verticalOffset,
                    head: [[section.title]],
                    body: section.data.map(item => [item]),
                    theme: 'grid',
                    headStyles: { fillColor: [22, 78, 99], textColor: 255 }, // Cyan-900
                    styles: { fontSize: 10, cellPadding: 4 },
                    margin: { top: 10 }
                })

                // @ts-ignore
                verticalOffset = doc.lastAutoTable.finalY + 15
            }
        })

        // Footer / Disclaimer
        doc.setFontSize(8)
        doc.setTextColor(150)
        const disclaimer = "DISCLAIMER: This report is generated by an AI system (MedScanX) and is for informational purposes only. It is NOT a substitute for professional medical advice, diagnosis, or treatment. Always consult with a qualified healthcare provider."
        const splitDisclaimer = doc.splitTextToSize(disclaimer, pageWidth - (margin * 2))

        doc.text(splitDisclaimer, margin, 280)

        // Save
        doc.save(`MedScanX_Report_${scan.scan_name.replace(/\s+/g, '_')}.pdf`)
    }

    return (
        <Button variant="outline" size="lg" onClick={generatePDF}>
            <span className="mr-2">📄</span>
            Download PDF Report
        </Button>
    )
}
